In [1]:
import numpy as np
import matplotlib.pyplot as plt

Matrix operation

In [7]:
a = np.array([[1,2]])
b = np.array([[4,-3]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5 -1]]
[[-3  5]]
[[ 4 -6]]
[[ 0.25       -0.66666667]]


In [8]:
print(np.shape(a))
print(np.shape(b))

(1, 2)
(1, 2)


In [11]:
b_t = np.transpose(b)
print(np.shape(b_t))
print(b_t)

(2, 1)
[[ 4]
 [-3]]


In [13]:
c = np.dot(a,b_t)
print(c)

[[-2]]


In [15]:
#sum 
np.sum(b)

1

In [16]:
#mean
np.mean(a)

1.5