In [234]:
# Knapsack GA
import numpy as np

In [235]:
# data
n = 4
c = 8
weight = np.array([1, 5, 3, 4])
value = np.array([15, 10, 9 ,5])

## Step 1: Define DNA


In [236]:
# dvar = [0, 1, 0, 1]
# w_tui = dvar * weight
# v_tui = dvar * value
mutation_rate = 0.5

class DNA:
    def __init__(self):
        self.dvar = np.random.randint(0,2,n)
        self.fitness = 0

    # Fitness function\
    def calc_fitness(self):
        w = np.sum(self.dvar * weight)
        self.fitness = np.sum(self.dvar*value)
        # penalty
        if w > c:
            self.fitness = self.fitness - (w-c)*5

    def mutate(self):
        for i in range(n):
            r = np.random.rand()
            if r<mutation_rate:
                #mutate
                self.dvar[i] = 1 - self.dvar[i]

In [237]:
a = DNA()
print(a.dvar)
a.calc_fitness()
print(a.fitness)

[1 0 0 1]
20


## initialize first population

In [238]:
population = []
pop_size = 10

for i in range(pop_size):
    population.append(DNA())
    population[i].calc_fitness()

In [239]:
for i in range(pop_size):
    print(population[i].dvar, population[i].fitness)

[0 1 1 1] 4
[0 1 1 0] 19
[1 0 0 1] 20
[1 0 0 1] 20
[1 0 0 0] 15
[1 0 1 1] 29
[1 1 1 1] 14
[0 0 1 0] 9
[1 1 0 1] 20
[0 0 0 0] 0


## MAIN LOOP

In [240]:
def crossover(d1, d2):
    mid = np.random.randint(0,n)
    new_dvar = np.concatenate([d1.dvar[0:mid], d2.dvar[mid:n]])
    result = DNA()
    result.dvar = new_dvar
    return result


In [241]:
from math import floor
num_of_iteration = 100

best_dna = DNA()
# best_dna.calc_fitness()

for it in range(num_of_iteration):
    print("Iteration:", it, "  ---  Best:", best_dna.fitness)
    ## create mating pool
    pool = []
    for i in range(pop_size):
        for j in range(floor((population[i].fitness))):
            pool.append(i)
    # print(np.shape(pool))
    ## Reproduction
    new_pop = []
    
    # break
    for i in range(pop_size):
        # Selection - Chon DNA tot
        id1 = np.random.choice(pool)
        id2 = np.random.choice(pool)
        # Crossover
        new_dna = crossover(population[id1], population[id2])
        # Mutation
        new_dna.mutate()
        new_dna.calc_fitness()
        new_pop.append(new_dna)
        # update best DNA
        if new_dna.fitness > best_dna.fitness:
            best_dna = new_dna
    population = new_pop

print(best_dna.dvar)
print(best_dna.fitness)

Iteration: 0   ---  Best: 0
Iteration: 1   ---  Best: 29
Iteration: 2   ---  Best: 29
Iteration: 3   ---  Best: 29
Iteration: 4   ---  Best: 29
Iteration: 5   ---  Best: 29
Iteration: 6   ---  Best: 29
Iteration: 7   ---  Best: 29
Iteration: 8   ---  Best: 29
Iteration: 9   ---  Best: 29
Iteration: 10   ---  Best: 29
Iteration: 11   ---  Best: 29
Iteration: 12   ---  Best: 29
Iteration: 13   ---  Best: 29
Iteration: 14   ---  Best: 29
Iteration: 15   ---  Best: 29
Iteration: 16   ---  Best: 29
Iteration: 17   ---  Best: 29
Iteration: 18   ---  Best: 29
Iteration: 19   ---  Best: 29
Iteration: 20   ---  Best: 29
Iteration: 21   ---  Best: 29
Iteration: 22   ---  Best: 29
Iteration: 23   ---  Best: 29
Iteration: 24   ---  Best: 29
Iteration: 25   ---  Best: 29
Iteration: 26   ---  Best: 29
Iteration: 27   ---  Best: 29
Iteration: 28   ---  Best: 29
Iteration: 29   ---  Best: 29
Iteration: 30   ---  Best: 29
Iteration: 31   ---  Best: 29
Iteration: 32   ---  Best: 29
Iteration: 33   ---  

In [242]:
pop_size
population[1].fitness

20

In [243]:
pool = [2,5,3,2,3]
print(np.random.choice(pool))

3
