In [1]:
import numpy as np

In [17]:
#data
n = 4
c = 8
weight = np.array([1, 5, 3, 4])
value = np.array([15, 10, 9 ,5])

In [18]:
solution = np.zeros((n+1,c+1))
print(solution)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
for k in range(1,n+1):
    for g in range(1, c+1):
        # print(k,g)
        if weight[k-1]>g:
            solution[k][g] = solution[k-1][g]
        else:
            solution[k][g] = max(value[k-1] + solution[k-1][g-weight[k-1]], solution[k-1][g])

print(solution)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 15. 15. 15. 15. 15. 15. 15. 15.]
 [ 0. 15. 15. 15. 15. 15. 25. 25. 25.]
 [ 0. 15. 15. 15. 24. 24. 25. 25. 25.]
 [ 0. 15. 15. 15. 24. 24. 25. 25. 29.]]


In [11]:
print("Best value =", solution[n][c])

Best value = 25.0
