In [1]:
import numpy as np

In [2]:
# ham fitness

def calc_fitness(x):
    z = x[0]*2 - 4*x[1] + 5*x[2] - 6*x[3]
    lhs1 = x[0] + 4*x[1] - 2*x[2] + 8*x[3]
    lhs2 = -x[0] + 2*x[1] + 3*x[2] + 4*x[3]
    rhs1 = 2
    rhs2 = 1
    d1 = lhs1-rhs1
    d2 = lhs2-rhs2
    if d1 > 0:
        z = z - 100*d1
    if d2 > 0:
        z = z - 100*d2
    # z = x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2
    return z
    

In [3]:
calc_fitness([58,0,3,0])

-4869

# PSO
## 1. Population Initialization
## 2. PSO main loop

In [4]:
from math import inf
# INitialization
pop_size = 200
n=4
dvar = np.random.random((pop_size,n))*10
velo = np.random.random((pop_size,n))*2
# calc fitness

# assign initial personal best
pbest = dvar
# find global best
best_id = 0
best_fit = -100000000
fitness = np.zeros(pop_size)
for i in range(pop_size):
    fitness[i] = calc_fitness(dvar[i])
    if fitness[i] > best_fit:
        best_id = i
        best_fit = fitness[i]
gbest = dvar[best_id]


In [5]:
print(best_fit)
print(gbest)

-616.3900287285062
[6.21145914 0.14322868 1.49442996 0.56595632]


### MAIN LOOP

In [14]:
num_of_iteration = 500
w = 1
c1 = 1.5
c2 = 1.5
wdamp = 0.995

for it in range(num_of_iteration):

    for i in range(pop_size):
        # update velocity
        velo[i] = w*velo[i] + c1 * (pbest[i] - dvar[i]) * np.random.rand() + c2 * (gbest-dvar[i]) * np.random.rand()
        velo[i] = np.maximum(velo[i],np.ones(n)*2)
        # update position
        dvar[i] = dvar[i] + velo[i]
        # update bound
        dvar[i] = np.maximum(dvar[i],0)
        # calculate fitness
        new_fitness = calc_fitness(dvar[i])
        if new_fitness > fitness[i]:
            pbest[i] = dvar[i]
        fitness[i] = new_fitness

        if fitness[i] > best_fit:
            gbest = dvar[i]
            best_fit = fitness[i]
        # break
        
    # update w
    w = w*wdamp
    print(w)
    # break


0.995
0.990025
0.985074875
0.9801495006250001
0.9752487531218751
0.9703725093562657
0.9655206468094844
0.960693043575437
0.9558895783575597
0.9511101304657719
0.946354579813443
0.9416228069143757
0.9369146928798039
0.9322301194154049
0.9275689688183278
0.9229311239742362
0.918316468354365
0.9137248860125932
0.9091562615825302
0.9046104802746175
0.9000874278732445
0.8955869907338783
0.8911090557802088
0.8866535105013078
0.8822202429488013
0.8778091417340573
0.8734200960253871
0.8690529955452602
0.8647077305675338
0.8603841919146962
0.8560822709551227
0.851801859600347
0.8475428503023453
0.8433051360508336
0.8390886103705794
0.8348931673187264
0.8307187014821328
0.8265651079747222
0.8224322824348486
0.8183201210226743
0.8142285204175609
0.810157377815473
0.8061065909263957
0.8020760579717637
0.798065677681905
0.7940753492934954
0.7901049725470279
0.7861544476842928
0.7822236754458713
0.778312557068642
0.7744209942832988
0.7705488893118823
0.7666961448653229
0.7628626641409962
0.759048350

In [15]:
print(gbest)

[1800. 1800. 1800. 1800.]


In [16]:
calc_fitness(gbest)

-3425100.0

In [13]:
fitness

array([-1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.        , -1522100.        ,
       -1522100.        , -1522100.     