In [206]:
import numpy as np

In [207]:
pop_size = 80
n = 4
dvar = np.random.random((pop_size,n))*100

In [208]:
print(np.floor(dvar))


[[55. 88. 45.  0.]
 [52. 90. 68. 49.]
 [59. 68. 39.  0.]
 [ 8. 12. 64. 82.]
 [60. 96. 43. 85.]
 [16. 56. 24.  7.]
 [ 5. 59. 52.  8.]
 [43. 78. 24. 14.]
 [89. 40. 64. 79.]
 [ 4. 36. 32. 40.]
 [ 1. 64. 20. 22.]
 [74. 27. 31. 25.]
 [26. 48. 39. 95.]
 [90. 62. 53. 29.]
 [26. 24. 17. 70.]
 [56. 75. 43. 33.]
 [31.  3. 78. 84.]
 [ 2. 12.  2. 37.]
 [34.  5. 45.  4.]
 [92.  1. 80. 20.]
 [ 8. 38. 99. 44.]
 [90. 96. 91.  1.]
 [50. 48. 13. 41.]
 [97. 98. 10. 35.]
 [ 5. 69. 28. 19.]
 [74. 85.  0. 62.]
 [82. 96. 97. 42.]
 [60. 11. 32. 52.]
 [97. 47. 68. 56.]
 [45.  8.  6. 92.]
 [61. 56. 97. 74.]
 [58. 96. 59. 47.]
 [70. 26.  8. 22.]
 [99. 76. 13. 83.]
 [86. 61. 34. 45.]
 [48.  7. 88. 10.]
 [59. 71. 59. 51.]
 [95. 40. 89. 71.]
 [31. 28. 44. 94.]
 [ 1. 39. 61. 65.]
 [35. 49. 87. 21.]
 [85. 89.  0. 22.]
 [46. 95. 36. 27.]
 [42. 55. 49. 40.]
 [87. 31. 96. 31.]
 [78.  3.  8. 96.]
 [44. 64.  1. 77.]
 [46. 98. 35.  0.]
 [14. 75.  7. 19.]
 [86. 55. 73.  9.]
 [64. 23.  2. 35.]
 [35. 15. 39. 73.]
 [69. 26. 12

In [209]:
z = dvar[:,0]*2 - 4*dvar[:,1] + 5*dvar[:,2] - 6*dvar[:,3]
print(z)

[ -22.1685863  -212.54304028   39.55792219 -207.85599446 -564.11817892
 -120.31947549  -16.37078905 -192.84816383 -138.8037037  -215.8543567
 -287.05859261   45.6291301  -512.88333595   24.14111933 -377.66190757
 -169.24050285  -62.3890925  -259.44236541  252.08137767  457.59694951
   94.19917328  244.85758969 -272.54306419 -360.03307904 -243.98527285
 -567.0147731    13.35300775  -75.81148012   12.20057243 -461.47669886
  -62.96136169 -255.61307283  -59.72412822 -544.02268354 -172.9668428
  449.26702018 -179.05312731   45.92835098 -392.38904079 -242.69871389
  182.17035398 -321.11686732 -273.49972641 -135.47672797  342.27751728
 -389.20182489 -627.79519847 -130.35296412 -352.04257739  263.67489518
 -165.58453104 -235.96648953 -436.77927927  168.01350588  -57.25278763
 -631.11419657    6.43949119  -31.76933991  -54.43538941  285.95386558
  385.92758436 -692.68054548  237.78949972   98.50000965 -143.69214304
   38.73602474 -342.70526639  -59.54363809 -205.32308782 -390.67374811
  341.85

In [210]:
lhs1 = dvar[:,0] + 4*dvar[:,1] - 2*dvar[:,2] + 8*dvar[:,3]
print(lhs1)

lhs2 = -dvar[:,0] + 2*dvar[:,1] - 3*dvar[:,2] + 4*dvar[:,3]
print(lhs2)

[ 326.31387031  676.78219432  258.87043755  593.13475647 1046.50406089
  256.67749481  207.15047871  428.3402572   760.68086259  409.4621633
  396.90510925  322.93127178  901.78320247  465.90908838  651.03119832
  537.87484667  563.30920276  347.25987867   -3.12810121  100.01357356
  319.41212115  303.56510209  549.12693751  755.40798159  384.00519974
  917.07059473  611.91299204  460.58578763  597.64842769  802.07514606
  688.65600866  707.04064033  341.36498329 1049.38707633  626.45182583
  -15.61745684  636.84580297  649.17541383  808.80746413  563.07225264
  231.75892917  624.59963371  574.3104089   490.077682    274.89406772
  843.71449592  921.51809298  375.6465398   456.21371798  235.47201789
  436.82561387  605.99288964  858.50203405  409.52986096  337.48846026
  771.83133898  433.44442707  360.71777834  166.84388681  304.17148158
  191.78252001 1053.41259756  326.83811524  436.51398356  605.88025869
  251.81119101 1005.90117413  574.00726382  482.84817465  826.97585999
   88.1

In [211]:
rhs1 = 2 * np.ones((1, pop_size))
rhs2 = 1 * np.ones((1, pop_size))

print(rhs1)

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 2.]]


In [212]:
d1 = lhs1-rhs1
d2 = lhs2-rhs2
print(np.shape(d1))
# print(d2)

(1, 80)


In [213]:
# FITNESS - max z

fitness = z - 2*d1 - 2*d2
print(np.shape(fitness))
print(fitness)

(1, 80)
[[ -647.40732751 -1803.55999372  -394.71111956 -1697.45934244
  -3343.34749577  -739.23425109  -406.20155331 -1241.53919116
  -1887.53491491 -1293.51474406 -1385.74307672  -567.75589348
  -2974.3045988   -882.252775   -2174.37379539 -1430.74088584
  -1335.40581391 -1280.0850184    554.33036585   760.86791533
   -433.74730323   -22.73464107 -1706.50679    -2285.45048193
  -1261.1728462  -3086.90423656 -1177.78545795 -1139.25082688
  -1208.50947763 -2698.9647485  -1549.27724863 -1955.13246286
   -833.4825007  -3335.67662959 -1649.58439129  1004.08082823
  -1669.1138286  -1254.36514438 -2539.76180079 -1675.41498381
    -48.56950889 -1929.97223941 -1707.66120251 -1276.58686134
    174.23131003 -2643.01440301 -3246.41098078  -972.27253716
  -1641.66628965   116.98951153 -1266.83956116 -1785.11396064
  -2749.46995646  -467.52590574  -768.15347682 -2908.19982982
   -895.04572554  -799.46640896  -439.11626832   -40.67689197
    409.80771008 -3653.71805241  -106.88216658  -654.20085533


In [214]:
# ham fitness

def calc_fitness(x):
    # z = x[0]*2 - 4*x[1] + 5*x[2] - 6*x[3]
    # lhs1 = x[0] + 4*x[1] - 2*x[2] + 8*x[3]
    # lhs2 = -x[0] + 2*x[1] + 3*x[2] + 4*x[3]
    # rhs1 = 2 * np.ones((1, pop_size))
    # rhs2 = 1 * np.ones((1, pop_size))
    # d1 = lhs1-rhs1
    # d2 = lhs2-rhs2
    # print(d1)
    # print(d2)
    # if d1 > 0:
    #     z = z - d1
    # if d2 > 0:
    #     z = z - d2
    x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2
    return z
    

In [215]:
calc_fitness([8,0,6,0])

array([ -22.1685863 , -212.54304028,   39.55792219, -207.85599446,
       -564.11817892, -120.31947549,  -16.37078905, -192.84816383,
       -138.8037037 , -215.8543567 , -287.05859261,   45.6291301 ,
       -512.88333595,   24.14111933, -377.66190757, -169.24050285,
        -62.3890925 , -259.44236541,  252.08137767,  457.59694951,
         94.19917328,  244.85758969, -272.54306419, -360.03307904,
       -243.98527285, -567.0147731 ,   13.35300775,  -75.81148012,
         12.20057243, -461.47669886,  -62.96136169, -255.61307283,
        -59.72412822, -544.02268354, -172.9668428 ,  449.26702018,
       -179.05312731,   45.92835098, -392.38904079, -242.69871389,
        182.17035398, -321.11686732, -273.49972641, -135.47672797,
        342.27751728, -389.20182489, -627.79519847, -130.35296412,
       -352.04257739,  263.67489518, -165.58453104, -235.96648953,
       -436.77927927,  168.01350588,  -57.25278763, -631.11419657,
          6.43949119,  -31.76933991,  -54.43538941,  285.95386

# PSO
## 1. Population Initialization
## 2. PSO main loop

In [216]:
from math import inf
# INitialization
dvar = np.random.random((pop_size,n))*10
velo = np.random.random((pop_size,n))*2
# calc fitness
fitness = calc_fitness(dvar)
# assign initial personal best
pbest = dvar
# find global best
best_id = 0
best_fit = -100000000
for i in range(pop_size):
    if fitness[0][i] > best_fit:
        best_id = i
        best_fit = fitness[0][i]
gbest = dvar[best_id]


IndexError: invalid index to scalar variable.

In [ ]:
print(gbest*np.ones((pop_size,n)))

[[5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 0.61393122 8.56483106 1.20597239]
 [5.84816634 

### MAIN LOOP

In [ ]:
num_of_iteration = 400
w = 1
c1 = 2
c2 = 2
wdamp = 0.9998

for it in range(num_of_iteration):
    # update velocity
    velo = w*velo + c1 * (pbest - dvar) * np.random.rand() + c2 * ((gbest*np.ones((pop_size,n)))-dvar) * np.random.rand()
    # update position
    dvar = dvar + velo
    # update bound
    dvar = np.maximum(dvar,0)
    # calculate fitness
    new_fitness = calc_fitness(dvar)

    for i in range(pop_size):
        if new_fitness[0][i] > fitness[0][i]:
            pbest[i] = dvar[i]

        if fitness[0][i] > best_fit:
            best_id = i
            best_fit = fitness[0][i]
    gbest = dvar[best_id]
    fitness = new_fitness
    # update w
    w = w*wdamp
    print(dvar[best_id])


[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.62871568     0.         18197.302956       0.        ]
[20227.6

In [ ]:
print(dvar[best_id])

[20227.62871568     0.         18197.302956       0.        ]


In [ ]:
pop_size = 1
calc_fitness(np.array([[8,0,10,0]]))

array([[52.]])