In [198]:
import numpy as np

In [199]:
# ham fitness

def calc_fitness(x):
    z = x[0]*2 - 4*x[1] + 5*x[2] - 6*x[3]
    lhs1 = x[0] + 4*x[1] - 2*x[2] + 8*x[3]
    lhs2 = -x[0] + 2*x[1] + 3*x[2] + 4*x[3]
    rhs1 = 2
    rhs2 = 1
    d1 = lhs1-rhs1
    d2 = lhs2-rhs2
    if d1 > 0:
        z = z - 10000*d1
    if d2 > 0:
        z = z - 10000*d2
    # z = x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2
    return z
    

In [200]:
calc_fitness([100,0,100,0])

-1989300

# PSO
## 1. Population Initialization

In [201]:
from math import inf
# INitialization
pop_size = 200
n=4
dvar = np.random.random((pop_size,n))*100
velo = np.random.random((pop_size,n))*10
# calc fitness

# assign initial personal best
pbest = np.random.random((pop_size,n))*100
# find global best
best_id = 0
best_fit = -100000000
fitness = np.zeros(pop_size)
pbest_fit = np.zeros(pop_size)
for i in range(pop_size):
    fitness[i] = calc_fitness(dvar[i])
    pbest_fit[i] = calc_fitness(pbest[i])
    if fitness[i] > best_fit:
        best_id = i
        best_fit = fitness[i]
gbest = dvar[best_id]


In [202]:
print(best_fit)
print(gbest)

-1297402.6904318044
[43.90649136  8.0059505  23.21402329  5.12538779]


## 2.MAIN LOOP

In [203]:
num_of_iteration = 500
w = 1
c1 = 1.5
c2 = 1.5
wdamp = 0.995

for it in range(num_of_iteration):

    for i in range(pop_size):
        # update velocity
        velo[i] = w*velo[i] + c1 * (pbest[i] - dvar[i]) * np.random.rand(n) + c2 * (gbest-dvar[i]) * np.random.rand(n)
        velo[i] = np.minimum(velo[i],np.ones(n)*10)
        velo[i] = np.maximum(velo[i],np.ones(n)*-10)
        # update position
        dvar[i] = dvar[i] + velo[i]
        # update bound
        dvar[i] = np.maximum(dvar[i],np.zeros(n))
        dvar[i] = np.minimum(dvar[i],np.ones(n)*100)
        # calculate fitness
        fitness[i] = calc_fitness(dvar[i])
        if fitness[i] > pbest_fit[i]:
            pbest[i] = dvar[i]
            pbest_fit[i] = fitness[i]
        if fitness[i] > best_fit:
            gbest = dvar[i]
            best_fit = fitness[i]
    # update w
    w = w*wdamp
    print(gbest[0], gbest[1], gbest[2], gbest[3], "->", best_fit)



53.90649136440202 18.005950503830718 21.98934597059502 15.125387785193258 -> -1297402.6904318044
63.85149136440202 27.950950503830718 20.771404371549135 25.070387785193258 -> -1297402.6904318044
69.57149515278326 33.25631990440563 20.116976476425034 27.623775223698974 -> -1297402.6904318044
59.57149515278326 23.25631990440563 20.686915305837353 17.623775223698974 -> -1297402.6904318044
53.73710385295214 1.0355180378564484 19.858560966791806 1.0008725735706996 -> -350624.7810628419
28.887772586936823 0.0 12.747394328802638 0.0 -> -97352.43077120847
25.198751249476885 0.0 17.160571628798877 0.0 -> -97352.43077120847
25.52371694783801 0.0 9.278067899708375 0.0 -> -62683.24122368954
16.002745575512535 0.0 5.349058817957425 0.0 -> -32987.528610736044
3.7371038529521385 0.0 1.3665314441298397 0.0 -> 14.306864926553477
0.0 0.0 0.0 0.0 -> 14.306864926553477
6.861747795021962 0.0 2.5602983080063577 0.0 -> 26.524987130075715
0.0 0.0 4.95663599949953 0.0 -> 26.524987130075715
0.0 0.0 4.6232610340

In [204]:
print(gbest)

[8. 0. 3. 0.]


In [205]:
calc_fitness(gbest)

30.999999999999787

In [206]:
fitness

array([30.99999381, 30.99999295, 30.99999993, 30.99999971, 30.99996305,
       30.99999935, 30.99999991, 31.        , 30.99998879, 30.99837831,
       31.        , 31.        , 30.99999997, 30.9998639 , 31.        ,
       31.        , 30.99998195, 30.9999916 , 30.99999993, 31.        ,
       30.99999999, 30.99986943, 30.99999814, 30.99999996, 30.99999999,
       31.        , 31.        , 30.99999757, 30.99999999, 31.        ,
       30.99999962, 30.99972318, 30.99999956, 30.99999952, 30.99999544,
       31.        , 31.        , 30.99999986, 30.99999823, 30.99986276,
       30.99999975, 30.99999978, 30.99999999, 30.99999933, 30.99996396,
       30.99999993, 31.        , 30.99990267, 30.99999898, 30.99999862,
       30.99999913, 31.        , 30.99999989, 31.        , 30.99999999,
       30.99724246, 30.99999999, 30.99996733, 30.999252  , 30.99998225,
       31.        , 30.99999328, 31.        , 31.        , 31.        ,
       30.99998853, 30.99999998, 30.99999754, 30.99602993, 31.  