In [54]:
import numpy as np

In [55]:
pop_size = 8
n = 4
dvar = np.random.random((pop_size,n))*100

In [56]:
print(np.floor(dvar))


[[56. 23. 54. 60.]
 [68. 13. 93. 90.]
 [15. 66. 46. 12.]
 [16. 62.  1. 63.]
 [42. 39. 82. 40.]
 [37. 91. 51. 43.]
 [21. 39. 93. 72.]
 [53. 71. 37. 61.]]


In [57]:
z = dvar[:,0]*2 - 4*dvar[:,1] + 5*dvar[:,2] - 6*dvar[:,3]
print(z)

[ -70.71680099    3.98809624  -79.82519294 -589.66184322   96.40034544
 -295.48968584  -83.05641803 -356.50681862]


In [58]:
lhs1 = dvar[:,0] + 4*dvar[:,1] - 2*dvar[:,2] + 8*dvar[:,3]
print(lhs1)

lhs2 = -dvar[:,0] + 2*dvar[:,1] - 3*dvar[:,2] + 4*dvar[:,3]
print(lhs2)

[525.02822789 662.62463422 290.2109101  772.26752944 362.52865263
 651.60514226 573.40324006 752.96521889]
[ 68.38347209  42.0963413   29.48969176 357.56463523 -48.66065662
 165.89707743  67.089714   220.56735009]


In [59]:
rhs1 = 2 * np.ones((1, pop_size))
rhs2 = 1 * np.ones((1, pop_size))

print(rhs1)

[[2. 2. 2. 2. 2. 2. 2. 2.]]


In [60]:
d1 = lhs1-rhs1
d2 = lhs2-rhs2
print(np.shape(d1))
# print(d2)

(1, 8)


In [61]:
# FITNESS - max z

fitness = z - 2*d1 - 2*d2
print(np.shape(fitness))
print(fitness)

(1, 8)
[[-1251.54020095 -1399.45385479  -713.22639666 -2843.32617255
   -525.33564658 -1924.49412521 -1358.04232615 -2297.57195659]]


In [62]:
# ham fitness

def calc_fitness(x):
    z = x[:,0]*2 - 4*x[:,1] + 5*x[:,2] - 6*x[:,3]
    lhs1 = x[:,0] + 4*x[:,1] - 2*x[:,2] + 8*x[:,3]
    lhs2 = -x[:,0] + 2*x[:,1] - 3*x[:,2] + 4*x[:,3]
    rhs1 = 2 * np.ones((1, pop_size))
    rhs2 = 1 * np.ones((1, pop_size))
    d1 = lhs1-rhs1
    d2 = lhs2-rhs2
    return z - 2*d1 - 2*d2
    